### PR TITLE
Fixed sox recording

### PR DESCRIPTION
**Pull request by MYXOMOPX**
Fixed arguments for sox recording. Sox is now default record program. Added option "audioType", that allows receive stream with any supported audio type.

### CODE REVIEW

**Comment by bahaa96** [comment]
Hey Guys please merge this PR the package is totally stopped.

**Comment by bcoe** [comment]
@gillesdemey I believe this might be an issue we've been bitten by too, bother you for a patch. I'm happy to help pitch in, in whatever way I can :smile:

**Comment by gillesdemey** [comment]
Will be fixed in https://github.com/gillesdemey/node-record-lpcm16/pull/39

**Comment by bcoe** [comment]
@gillesdemey :+1: thank you for the hard work.

**Pull request closed without merging**
