### PR TITLE
Fixes crashes when recording again && stopping non-recording 'rec'

### PR DESCRIPTION
**Pull request by cauli**
Fixes issues #3 and #4

### CODE REVIEW

**Comment by gillesdemey** [comment]
Nice contribution, I'll check out the code this weekend though it seems like a no-brainer :)

**Comment by gillesdemey** [comment]
I'll just accept this PR and clean that up, unless you want to add another commit to this PR?

**Comment by cauli** [comment]
I'll do that, just a sec! (:

**Comment by Glavin001** [comment]
It appears this has not been published to npm! It is causing my app to break and making [this PR for node-wit invalid](https://github.com/wit-ai/node-wit/pull/8). Please publish soon! I am using this package in an app for a hackathon this week.

For now, I am going to use the Git repository directly and not npm.

**Comment by gillesdemey** [comment]
I've published version 0.1.4 to npm!

**Pull request merged**
